server:
  port: ${PORT:8080}

spring:

  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:secret}
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
