server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: secret

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
